# fly.toml app configuration file generated for game-server-achtung on 2025-08-24T22:20:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'game-server-achtung'
primary_region = 'arn'

[build]
dockerfile = '../apps/game-server/Dockerfile'

[env]
GAME = 'achtung'
NUM_PLAYERS = '8'
PORT = '80'
RUST_LOG = 'info'
TICK_RATE_MS = '50'

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
