# fly.toml app configuration file generated for achtung on 2025-08-24T21:31:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'achtung-overseer'
primary_region = 'arn'

[build]
dockerfile = '../apps/overseer/Dockerfile'

[env]
PORT = '50051'
REGISTRY_URL = 'https://achtung-registry.fly.dev'

[[services]]
protocol = "tcp"
internal_port = 50051
auto_stop_machines = "stop"
auto_start_machines = true
max_machines_running = 1
min_machines_running = 0
processes = ["app"]

[[services.ports]]
port = 50051

[[vm]]
size = 'shared-cpu-1x'
