[package]
name = "overseer"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
